### ISSUE TITLE
File replacement is not proper

### ISSUE THREAD

**Issue by manohartn** [basti1302/grunt-version-assets#2]
Suppose i have two files : 
1) abc/def/xyz.js
2) ghi/klm/xyz.js 
(Notice there are two different files (but of same file names - xyz.js) in two different paths and if i have both the files included in my jsp, both the files are replaced with same hashed version although they two hash to two different hash

**Comment by basti1302** [comment]
This would be a bug in https://github.com/techjacker/node-version-assets. Please [file](https://github.com/techjacker/node-version-assets/issues/new) the issue there.

grunst-version-assets is only a thin wrapper around node-version-assets.
